In [9]:
#2.1
#sample
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



In [8]:
#sample
import numpy as np
# Create arrays of different dimensions
array_0d = np.array(5)
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# Print arrays with shapes
for i, arr in enumerate([array_0d, array_1d, array_2d, array_3d]):
    print(f"{i}D Array:\n{arr}\nShape: {arr.shape}\n")

0D Array:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)



In [10]:
#sample
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
reshaped_array = array.reshape(3, 2) # Reshape to (3, 2), keeping 6 elements
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


In [12]:
#3.1
#sanmple
import numpy as np
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [13]:
#smaple
import numpy as np
# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))


[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [25]:
#sample
import numpy as np
ones_array = np.ones((2, 3)) # Shape: (2, 3)
zeros_array = np.zeros((3, 2)) # Shape: (3, 2)
empty_array = np.empty((2, 2)) # Shape: (2, 2)
identity_matrix = np.eye(3) # Shape: (3, 3)
print(ones_array, zeros_array, empty_array, identity_matrix, sep="\\n\n")

[[1. 1. 1.]
 [1. 1. 1.]]\n
[[0. 0.]
 [0. 0.]
 [0. 0.]]\n
[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]\n
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
#sample
import numpy as np
array_from_list = np.array([1, 2, 3]) # [1 2 3]
array_from_tuple = np.array((4, 5, 6)) # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]]) # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple, array_from_nested_list, sep="\n")

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [26]:
#sample
import numpy as np
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) # Shape: (2,3)
print(arr, zeros, ones, empty, sep="\n")

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2.65252485e-312 7.24707650e-310 1.51274777e-311]
 [7.24728787e-310 1.51270859e-311 1.51271146e-311]]


In [29]:
#sample
import numpy as np
array = np.array([1, 2, 3])
# Multiplies each element by 2, result: [2, 4, 6]
new_array = array * 2
# Creates a new array with the same elements
copied_array = np.copy(array)
# Slices elements from index 1 to 3, result:[2]
sliced_array = array[1:2]

In [30]:
#sample
import numpy as np
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Concatenate along axis 0 (vertical) Shape: (4, 2)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Concatenate along axis 1 (horizontal) Shape: (2, 4)
print(concat_axis0, concat_axis1, sep="\n")

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [31]:
#sample
import numpy as np
# Arrays
arr1d = np.array([0, 1, 2, 3, 4, 5])
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr3d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8, 9], [10, 11]]])
# Slicing examples
print("Basic:", arr1d[1:4], arr2d[1:3, 0:2], arr3d[1:2, 0:2, 1:2])
# Output Basic: arr1d:[1 2 3] arr2d:[[3 4] [6 7]] arr3d:[[[5] [7]]]
print("Step:", arr1d[1:5:2], arr2d[::2, 1::2], arr3d[::2, ::2, 1::2])
# Output: Step: [1 3] [[1] [7]] [[[1] [9]]]

Basic: [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]
Step: [1 3] [[1]
 [7]] [[[1]]

 [[9]]]


In [32]:
#sample
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Add:", np.add(arr1, arr2)) # Output Add: [5 7 9]
print("Subtract:", np.subtract(arr1, arr2))
# Output Subtract: [-3 -3 -3]
print("Divide:", np.divide(arr1, arr2))
# Output Divide: [0.25 0.4 0.5 ]
print("Multiply:", np.multiply(arr1, arr2))
# Output Multiply: [ 4 10 18]
print("Power:", np.power(arr1, arr2))
# Output Power: [ 1 32 729]
print("Exp:", np.exp(arr1))
# Output Exp: [ 2.71828183 7.3890561 20.08553692]

Add: [5 7 9]
Subtract: [-3 -3 -3]
Divide: [0.25 0.4  0.5 ]
Multiply: [ 4 10 18]
Power: [  1  32 729]
Exp: [ 2.71828183  7.3890561  20.08553692]


In [33]:
#sample
import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using np.dot
result_dot = np.dot(A, B)
print("Result with np.dot:\n", result_dot) # Output shape: (2, 2)

Result with np.dot:
 [[ 58  64]
 [139 154]]


In [34]:
#sample
import numpy as np
# Define two matrices
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
# Matrix multiplication using @ operator
result_at = A @ B
print("Result with @ operator:\n", result_at) # Output shape: (2, 2)
# Matrix multiplication using np.matmul
result_matmul = np.matmul(A, B)
print("Result with np.matmul:\n", result_matmul) # Output shape: (2, 2)

Result with @ operator:
 [[ 58  64]
 [139 154]]
Result with np.matmul:
 [[ 58  64]
 [139 154]]


In [36]:
#sample
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
print("Inverse:\n", np.linalg.inv(A))
# Output: Inverse: [[-2. 1. ], [ 1.5 -0.5]]
print("Determinant:", np.linalg.det(A))
# Output: Determinant: -2.0
print("Frobenius Norm:", np.linalg.norm(A, "fro"))
# Output: Frobenius Norm: 5.4772
print("2-Norm (Euclidean):", np.linalg.norm(A))
# Outptut: 2-Norm(Euclidean): 5.4772
print("Solution x:", np.linalg.solve(A, B))
#Output: Solution x: [-4. 4.5]

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]


In [37]:
#4.1
#problem 1
# 1.
import numpy as np
empty_array = np.empty((2, 2))
print("Empty 2x2 array:\n", empty_array)

Empty 2x2 array:
 [[1. 2.]
 [3. 4.]]


In [38]:
# 2.
ones_array = np.ones((4, 2))
print("\nOnes 4x2 array:\n", ones_array)


Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [39]:
# 3.
shape = (3, 3)
fill_value = 7
full_array = np.full(shape, fill_value)
print("\nFull array 3x3 filled with 7:\n", full_array)


Full array 3x3 filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [40]:
# 4. 
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros-like array:\n", zeros_like_array)


Zeros-like array:
 [[0 0]
 [0 0]]


In [41]:
# 5. 
ones_like_array = np.ones_like(given_array)
print("\nOnes-like array:\n", ones_like_array)



Ones-like array:
 [[1 1]
 [1 1]]


In [42]:
# 6.
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print("\nConverted numpy array:\n", np_array)


Converted numpy array:
 [1 2 3 4]


In [43]:
#problem 2
#1.
import numpy as np
arr1 = np.arange(10, 50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [44]:
# 2.
arr2 = np.arange(9).reshape(3, 3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [45]:
# 3.
arr3 = np.eye(3)
print(arr3)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
# 4.
arr4 = np.random.random(30)
print("Mean:", arr4.mean())

Mean: 0.4679588107860224


In [48]:
# 5.
arr5 = np.random.random((10, 10))
print("Min:", arr5.min())
print("Max:", arr5.max())

Min: 0.05108299928812354
Max: 0.9897949093491196


In [49]:
# 6.
arr6 = np.zeros(10)
arr6[4] = 1    # 5th element (index 4)
print(arr6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [50]:
# 7.
arr7 = np.array([1, 2, 0, 0, 4, 0])
print(arr7[::-1])

[0 4 0 0 2 1]


In [51]:
# 8.
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print(arr8)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [52]:
# 9.
arr9 = np.zeros((8, 8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print(arr9)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [1]:
#problem 3
# 1.
import numpy as np
arr1 = np.arange(10, 50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [2]:
# 2.
arr2 = np.arange(9).reshape(3, 3)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
# 3.
arr3 = np.eye(3)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
#4.
arr4 = np.random.random(30)
print("Mean:", arr4.mean())

Mean: 0.4402246960446463


In [5]:
# 5.
arr5 = np.random.random((10, 10))
print("Min:", arr5.min())
print("Max:", arr5.max())

Min: 0.0009131295002016149
Max: 0.9908802626616418


In [6]:
# 6.
arr6 = np.zeros(10)
arr6[4] = 1    # 5th element (index 4)
print(arr6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
# 7.
arr7 = np.array([1, 2, 0, 0, 4, 0])
print(arr7[::-1])

[0 4 0 0 2 1]


In [8]:
# 8.
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print(arr8)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
# 9.
arr9 = np.zeros((8, 8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print(arr9)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [10]:
#problem 4
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [11]:
A_inv = np.linalg.inv(A)
result = A @ A_inv
result = np.round(result).astype(int)

identity = np.eye(2, dtype = int)

print("A * A^-1 =\n", result, "\nI =\n", identity)
if (np.array_equal(result, identity)):
  print("A * A^-1 = I")

A * A^-1 =
 [[1 0]
 [0 1]] 
I =
 [[1 0]
 [0 1]]
A * A^-1 = I


In [12]:
AB = A @ B
BA = B @ A

print("AB =\n", AB, "\n\nBA =\n", BA)
print("\n")
print("A * B = B * A:", np.array_equal(AB, BA))

AB =
 [[23 13]
 [51 29]] 

BA =
 [[36 44]
 [13 16]]


A * B = B * A: False


In [13]:
LHS = (A @ B).T
RHS = B.T @ A.T

print("LHS =\n", LHS, "\nRHS =\n", RHS)
if (np.array_equal(LHS, RHS)):
  print("(A.B)T (LHS) = (B)T.(A)T (RHS)")

LHS =
 [[23 51]
 [13 29]] 
RHS =
 [[23 51]
 [13 29]]
(A.B)T (LHS) = (B)T.(A)T (RHS)


In [14]:
"""
Equations:
2x - 3y + z = -1
 x - y + 2z = -3
3x + y -  z =  9

"""

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]], dtype=float)

B = np.array([-1, -3, 9], dtype=float)

# AX = B
# X = A^-1 . B
# Finding X using np.linalg.inv()

A_inverse = np.linalg.inv(A)
X = A_inverse @ B
print("Using inverse matrix method:\n x = {:.2f}\n y = {:.2f}\n z = {:.2f}".format(X[0], X[1], X[2]))

Using inverse matrix method:
 x = 2.00
 y = 1.00
 z = -2.00


In [15]:
X_solve = np.linalg.solve(A, B)
print("Using np.linalg.sovle():\n x = {:.2f}\n y = {:.2f}\n z = {:.2f}".format(X[0], X[1], X[2]))

Using np.linalg.sovle():
 x = 2.00
 y = 1.00
 z = -2.00


In [16]:
import time

# python lists
list1 = list(range(1000000))
list2 = list(range(1000000))

# numpy arrays
array1 = np.arange(1000000)
array2 = np.arange(1000000)

In [17]:
# python lists
start = time.time()
list_add = [list1[i] + list2[i] for i in range(1000000)]
end = time.time()
print("Time for element-wise addition of python lists:", end - start, "s")

# numpy arrays
start = time.time()
array_add = array1 + array2
end = time.time()

print("Time for element-wise addition of numpy arrays:", end - start, "s")

Time for element-wise addition of python lists: 0.2022101879119873 s
Time for element-wise addition of numpy arrays: 0.005835533142089844 s


In [18]:
# python lists
start = time.time()
list_multiply = [list1[i] * list2[i] for i in range(1000000)]
end = time.time()
print("Time for element-wise multiplication of python lists:", end - start, "s")

# numpy arrays
start = time.time()
array_multiply = array1 * array2
end = time.time()

print("Time for element-wise multiplication of numpy arrays:", end - start, "s")

Time for element-wise multiplication of python lists: 0.22080540657043457 s
Time for element-wise multiplication of numpy arrays: 0.006193876266479492 s


In [19]:
# python lists
start = time.time()
list_dot = sum(list1[i] * list2[i] for i in range(1000000))
end = time.time()
print("Time for dot-product of python lists:", end - start, end="s\n")

# numpy arrays
start = time.time()
array_dot = np.dot(array1, array2)
end = time.time()

print("Time for dot-product of numpy arrays:", end - start, end="s\n")

Time for dot-product of python lists: 0.15379834175109863s
Time for dot-product of numpy arrays: 0.0024139881134033203s


In [20]:
# python matrices
python1 = [[1 for _ in range(1000)] for _ in range(1000)]
python2 = [[1 for _ in range(1000)] for _ in range(1000)]
start = time.time()
python3 = [[sum(python1[i][k] * python2[k][j] for k in range(1000))
           for j in range(1000)] for i in range(1000)]
end = time.time()

print("Time for python matrix multiplication:", end - start, "s")

# numpy matrices
np1 = np.ones((1000, 1000))
np2 = np.ones((1000, 1000))

start = time.time()
np3 = np1 @ np2
end = time.time()

print("Time for numpy matrix multiplication:", end - start, "s")

Time for python matrix multiplication: 115.17155838012695 s
Time for numpy matrix multiplication: 0.012237071990966797 s
